In [ ]:
# importando as bibliotecas
import numpy as np
import pandas as pd

In [ ]:
# Código 1

Z = np.zeros((4,))
print("Z:", Z)

Z: [0. 0. 0. 0.]


In [ ]:
# CÓDIGO 2
Z = np.zeros((4,))
Z[1] = 1.
print("Z:", Z)

Z: [0. 1. 0. 0.]


In [ ]:
# CÓDIGO 3
Z = np.zeros((4,))
Z[1:] = 1.
print("Z:", Z)

Z: [0. 1. 1. 1.]


In [ ]:
# CÓDIGO 4
# Z = Z = np.zeros((4,))
# Z[:3] = 1.
# print("Z:", Z)

Z: [1. 1. 1. 0.]


In [ ]:
Z = np.zeros((4, )) 
Z[:-1] = 1.
print(Z)

[1. 1. 1. 0.]


In [ ]:
Z = np.zeros((4, )) 
Z[:3] = 1.
print(Z)

[1. 1. 1. 0.]


In [ ]:
Z = np.ones((4,)) 
Z[4] = 0.
print(Z)

IndexError: ignored

In [ ]:
Z = np.ones((4,)) 
Z[-1] = 0.
print(Z)

[1. 1. 1. 0.]


In [ ]:
# # CÓDIGO 5
# X = 2 * np.ones((2,2))
# print("X:\n", X)

X:
 [[2. 2.]
 [2. 2.]]


In [ ]:
X = np.twos((2, 2))

AttributeError: ignored

In [ ]:
# CÓDIGO 6
X = np.array([[1,2], [3,4]])
Y = X[0, :]
Y[1] = 10
print("X:\n", X)

X:
 [[ 1 10]
 [ 3  4]]


In [ ]:
# CÓDIGO 7
X = np.array([[1,3], [11,10]])
print(np.mean(X[X>np.pi]))

10.5


In [ ]:
# CÓDIGO 8
data = {'animal':['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age':[2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits':[1,3,2,3,2,3,1,1,2,1],
        'priority':['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [ ]:
pd.DataFrame(data=data, index  = labels)

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

In [ ]:
# CÓDIGO 9
df = pd.DataFrame(data=data, index=labels)

In [ ]:
df.shape

(10, 4)

In [ ]:
pergunta = df['animal'].value_counts()
type(pergunta)

pandas.core.series.Series

In [ ]:
print(pergunta)

dog      4
cat      4
snake    2
Name: animal, dtype: int64


In [ ]:
df.describe()

age     visits
count  8.000000  10.000000
mean   3.437500   1.900000
std    2.007797   0.875595
min    0.500000   1.000000
25%    2.375000   1.000000
50%    3.000000   2.000000
75%    4.625000   2.750000
max    7.000000   3.000000

In [ ]:
df.iloc[:, 3]

a    yes
b    yes
c     no
d    yes
e     no
f     no
g     no
h    yes
i     no
j     no
Name: priority, dtype: object

In [ ]:
df.sort_values(by='visits', ascending=False)

animal  age  visits priority
b    cat  3.0       3      yes
d    dog  NaN       3      yes
f    cat  2.0       3       no
c  snake  0.5       2       no
e    dog  5.0       2       no
i    dog  7.0       2       no
a    cat  2.5       1      yes
g  snake  4.5       1       no
h    cat  NaN       1      yes
j    dog  3.0       1       no

In [ ]:
# CÓDIGO 10
y_true = np.array([1., 2., 1.])
y_pred = np.array([1.1, 1.98, 1.05])

In [ ]:
np.sqrt(((y_true-y_pred)**2).mean())

0.06557438524302006